#!/usr/bin/python
import subprocess 
import sys
import webbrowser
from time import sleep
from daemon import Daemon

sites = ('https://threatmap.checkpoint.com/','https://google.com')#Agregar urls aquí
wait_time = 2#tiempo en segundos

browser = 'firefox'
brow = webbrowser.get(browser)# Navegador a utilizar, firefox da mejores resultados
workspaces = len(sites)

class Dashboard(Daemon):
    def run(self):
        try:
            for i,site in enumerate(sites):
                    subprocess.Popen(f'wmctrl -s {i+1}'.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
                    brow.open(site, new=1, autoraise=True)
                    sleep(2)
                    subprocess.Popen(f'xdotool key F11'.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
                    sleep(2)

            while True:
                for i in range(workspaces):
                    subprocess.Popen(f'wmctrl -s {i+1}'.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
                    sleep(wait_time)
        except Exception as e:
            print(e)
            #subprocess.Popen(f'killall firefox'.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
            
            print('Programa terminado')

if __name__ == '__main__':
    dashboard = Dashboard('/tmp/dashboard.pid','/tmp/dashboard.date',stdout='/tmp/dashboard.log')
    if sys.argv[1] == 'start':
            dashboard.start()
    elif sys.argv[1] == 'stop':
            dashboard.stop()
    elif sys.argv[1] == 'restart':
            dashboard.restart()
    elif sys.argv[1] == 'run':
            dashboard.run()
    elif sys.argv[1] == 'running':
            dashboard.is_running()
    else:
        print('No se escogió una opción adecuada')



